[Content]
Packages=
         # task-desktop + lxqt-core + pavucontrol + powermanagement + sddm
         # + lxqt-sudo + lxqt-askpass + qterminal + debian-branding
         task-lxqt-desktop
         xfwm4
         xfwm4-theme-breeze
         sddm-theme-maya
         # xfce4 plugins
         gvfs-backends
         gvfs-fuse
         lxqt-policykit
         lxqt-sudo
         qlipper
         # Themes
         lxqt-theme-debian
         lxqt-themes
         breeze-icon-theme
         adwaita-qt
         adwaita-qt6
         # Wayland session
         lxqt-wayland-session
         labwc
         # Video player
         smplayer
         plymouth
         # For flatpak
         xdg-desktop-portal-lxqt
