[Match]
Distribution=debian

[Content]
Packages=
        mesa-utils
        va-driver-all
        mesa-vulkan-drivers
        rfkill
        iwd
        network-manager
        network-manager-iwd
        network-manager-tui

