[Content]
Packages=
         task-desktop
         labwc
         # Bar
         waybar
         # Terminal
         foot
         # Notification daemon
         mako-notifier
         # Wallpaper
         swaybg
         # Screenlock
         swayidle
         gvfs-backends
         gvfs-fuse
         # Display manager
         wlgreet
