[Content]
Packages=
    firmware-linux
    firmware-linux-nonfree
    live-task-non-free-firmware-pc
    live-task-non-free-firmware-server
    bluez-firmware
    firmware-atheros
    firmware-brcm80211
    firmware-intel-sound
    firmware-ipw2x00
    firmware-iwlwifi
    # Recommended by firmware-linux-free
    firmware-carl9170
    firmware-ath9k-htc
    firmware-realtek
    firmware-sof-signed
    # Recommended by firmware-misc-nonfree
    firmware-nvidia-graphics
    firmware-intel-graphics
    firmware-amd-graphics
    firmware-intel-misc
    firmware-mediatek
    # Others
    firmware-nvidia-gsp
    # Provides regulatory.db
    wireless-regdb
