[Content]
Packages=
         # task-desktop + kde-standard + sddm
         task-kde-desktop
         sddm-theme-debian-breeze
         ocean-sound-theme
         breeze-gtk-theme
         xdg-desktop-portal-kde
         bluedevil
         powerdevil
         kwin-addons
         kde-config-gtk-style
         kde-config-gtk-style-preview
         kde-config-sddm
         kde-config-flatpak
         ark
         kinfocenter
         kscreen
         ksshaskpass
         kwallet6
         kwrited
         plasma-disks
         plasma-nm
         plasma-pa
         plasma-thunderbolt
         plasma-systemmonitor
         plasma-welcome
         plasma-workspace-wallpapers
         kgamma
         konsole
         dolphin
         kde-spectacle
         plasma-discover
         drkonqi
         print-manager
